

Vagrant::Config.run do |config|

  config.vm.box = "precise64"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"
  

  config.vm.network :hostonly, "192.168.50.1"
  config.vm.forward_port 27017, 27017
  config.vm.forward_port 27018, 27018

  config.vm.share_folder "v-data", "/home/vagrant/data", "../data"
  config.vm.provision :chef_solo do |chef|
  config.vm.host_name = "mongo"  
  chef.add_recipe "mongodb"


  end
end
